"""Remove team_id from members table

Revision ID: 1a9ce04bf29e
Revises: b61146000770
Create Date: 2025-07-20 21:50:26.953151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9ce04bf29e'
down_revision: Union[str, Sequence[str], None] = 'b61146000770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('members_team_id_fkey'), 'members', type_='foreignkey')
    op.drop_column('members', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('members_team_id_fkey'), 'members', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
