"""remove is_main boolean on Character

Revision ID: 311de8f59804
Revises: 40e4f448e81b
Create Date: 2025-07-21 19:17:52.294581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311de8f59804'
down_revision: Union[str, Sequence[str], None] = '40e4f448e81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toons', 'is_main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toons', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
