"""add scenario templating with mop support and raid scenario fields

Revision ID: 40e4f448e81b
Revises: 388d26d02fb8
Create Date: 2025-07-21 18:31:17.877446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e4f448e81b'
down_revision: Union[str, Sequence[str], None] = '388d26d02fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raids', sa.Column('scenario_name', sa.String(length=100), nullable=False))
    op.add_column('raids', sa.Column('scenario_difficulty', sa.String(length=16), nullable=False))
    op.add_column('raids', sa.Column('scenario_size', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('raids_scenario_id_fkey'), 'raids', type_='foreignkey')
    op.drop_column('raids', 'scenario_id')
    op.add_column('scenarios', sa.Column('mop', sa.Boolean(), nullable=False))
    op.drop_column('scenarios', 'size')
    op.drop_column('scenarios', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('difficulty', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('scenarios', sa.Column('size', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_column('scenarios', 'mop')
    op.add_column('raids', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('raids_scenario_id_fkey'), 'raids', 'scenarios', ['scenario_id'], ['id'])
    op.drop_column('raids', 'scenario_size')
    op.drop_column('raids', 'scenario_difficulty')
    op.drop_column('raids', 'scenario_name')
    # ### end Alembic commands ###
