"""Add Toon model

Revision ID: 70e1f0383441
Revises: f69d0168ab90
Create Date: 2025-07-13 23:34:49.408402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e1f0383441'
down_revision: Union[str, Sequence[str], None] = 'f69d0168ab90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('class', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("class IN ('Death Knight', 'Warrior', 'Druid', 'Paladin', 'Monk', 'Rogue', 'Hunter', 'Mage', 'Warlock', 'Priest', 'Shaman')", name='ck_toon_class_valid'),
    sa.CheckConstraint("role IN ('DPS', 'Healer', 'Tank')", name='ck_toon_role_valid'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'username', name='uq_toon_member_username')
    )
    op.create_index(op.f('ix_toons_id'), 'toons', ['id'], unique=False)
    op.create_index(op.f('ix_toons_member_id'), 'toons', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toons_member_id'), table_name='toons')
    op.drop_index(op.f('ix_toons_id'), table_name='toons')
    op.drop_table('toons')
    # ### end Alembic commands ###
