"""Remove unique constraint from Scenario names

Revision ID: d9b48902e99a
Revises: 6156cba21210
Create Date: 2025-07-18 00:45:46.064715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b48902e99a'
down_revision: Union[str, Sequence[str], None] = '6156cba21210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_name'), table_name='scenarios')
    op.create_index(op.f('ix_scenarios_name'), 'scenarios', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_name'), table_name='scenarios')
    op.create_index(op.f('ix_scenarios_name'), 'scenarios', ['name'], unique=True)
    # ### end Alembic commands ###
