"""add_superuser_invite_field

Revision ID: f010aacf9088
Revises: 23fc8a6542a4
Create Date: 2025-08-03 20:33:03.616268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f010aacf9088'
down_revision: Union[str, Sequence[str], None] = '23fc8a6542a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('invites', sa.Column('is_superuser_invite', sa.Boolean(), nullable=True))
    
    # Update existing rows with default value
    op.execute("UPDATE invites SET is_superuser_invite = false WHERE is_superuser_invite IS NULL")
    
    # Make column not null
    op.alter_column('invites', 'is_superuser_invite', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'is_superuser_invite')
    # ### end Alembic commands ###
