"""Move difficulty and size from raid to scenario

Revision ID: 6156cba21210
Revises: 64716582e5c9
Create Date: 2025-07-17 21:01:12.606156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6156cba21210'
down_revision: Union[str, Sequence[str], None] = '64716582e5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raids', 'difficulty')
    op.drop_column('raids', 'size')
    op.add_column('scenarios', sa.Column('difficulty', sa.String(length=16), nullable=False))
    op.add_column('scenarios', sa.Column('size', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'size')
    op.drop_column('scenarios', 'difficulty')
    op.add_column('raids', sa.Column('size', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('raids', sa.Column('difficulty', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
