"""Add warcraftlogs_url to Raid model

Revision ID: f5c6ecaf8632
Revises: d9b48902e99a
Create Date: 2025-07-18 02:43:08.325137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c6ecaf8632'
down_revision: Union[str, Sequence[str], None] = 'd9b48902e99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raids', sa.Column('warcraftlogs_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raids', 'warcraftlogs_url')
    # ### end Alembic commands ###
